# This is a basic workflow that is manually triggered

name: Slack Notification

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

env:
  SLACK_USERNAME: PushBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION }}

on:
  push:
    branches: 
      - 'main'
  pull_request:
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    name: Slack-Notification
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v4

    - name: Slack Notification on Success
      uses: rtCamp/action-slack-notify@v2
      if: ${{ success() }}
      env:
        SLACK_TITLE: Push
        SLACK_COLOR: good
        SLACK_MESSAGE: mainブランチにpushされました🚀
